### ISSUE TITLE
string-replace is void, maybe replace-regexp-in-string ?

### ISSUE THREAD

**Issue by jiacai2050** [xuchunyang/osx-dictionary.el#25]
```
Debugger entered--Lisp error: (void-function string-replace)
  string-replace("·" "" #("point" 0 5 (fontified t)))
  osx-dictionary--get-current-word()
  osx-dictionary-open-dictionary\.app()
  funcall-interactively(osx-dictionary-open-dictionary\.app)
  call-interactively(osx-dictionary-open-dictionary\.app nil nil)
  command-execute(osx-dictionary-open-dictionary\.app)

```

**Comment by xuchunyang** [comment]
Oops, I didn't review the last pull request carefully, there is no such function, such issue can be discovered in CI test if the project has one, I will fix it within today.

**Comment by jiacai2050** [comment]
Thanks.

After upgrade to 20210308.632, it seems that 
osx-dictionary-search-word-at-point is aliased, and not 
autoloaded, this is a breaking change for me, perhaps auto load 
this alias?

**Comment by xuchunyang** [comment]
> After upgrade to 20210308.632, it seems that osx-dictionary-search-word-at-point is aliased, and not autoloaded, this is a breaking change for me, perhaps auto load this alias?

Done in the latest commit 4d4cc19fdd4ac8408bd5acc7694e7a7096b1e3b3.
