### ISSUE TITLE
Fail to get word under point

### ISSUE THREAD

**Issue by cxa** [xuchunyang/osx-dictionary.el#35]
Fail to get word under point in Emacs 29.3, this line is problematic:

https://github.com/xuchunyang/osx-dictionary.el/blob/8f16ffb465b64c9dd566c8b7316b34896ce4c52b/osx-dictionary.el#L152

Works again after I comment it out.

**Comment by xuchunyang** [comment]
I don't know how to reproduce.

and it seems `osx-dictionary--get-current-word` is only called in the osx-dictionary major mode.

https://github.com/xuchunyang/osx-dictionary.el/blob/8f16ffb465b64c9dd566c8b7316b34896ce4c52b/osx-dictionary.el#L150-L153

**Comment by cxa** [comment]
Apologies, I provided incorrect information. I attributed the issue to the wrong cause before identifying the actual compiling problem.
