### ISSUE TITLE
Feature request: search a word in all dictionaries.

### ISSUE THREAD

**Issue by jiegec** [xuchunyang/osx-dictionary.el#8]
Only need to feed the output of the cli -l to osx-dictionary-dictionary-choice. Writing a pull request.

**Comment by jiegec** [comment]
Wait I see a function: osx-dictionary--list-dictionaries

**Comment by jiegec** [comment]
Done in https://github.com/xuchunyang/osx-dictionary.el/pull/9

**Comment by jiegec** [comment]
Btw, the osx-dictionary-cli.m is highly undocumented. It is hard to maintain.

**Comment by xuchunyang** [comment]
> Btw, the osx-dictionary-cli.m is highly undocumented. It is hard to maintain.

I agree.
